# Project identification
sonar.projectKey=legend-shared
sonar.organization=finos
sonar.projectName=Legend Shared

# Source configuration
sonar.sources=.
sonar.inclusions=**/src/main/java/**

# Test configuration
sonar.tests=.
sonar.test.inclusions=**/src/test/java/**

# Binaries (standard Maven compiled output)
sonar.java.binaries=artifacts/
sonar.java.libraries=artifacts/

#Test Reports
sonar.junit.reportPaths=test-reports/junit/
sonar.coverage.jacoco.xmlReportPaths=legend-shared-test-reports/target/site/jacoco-aggregate/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8
